# Generated by Django 5.2.2 on 2025-06-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(choices=[('101', '101'), ('102', '102'), ('K103', 'K103')], max_length=10, unique=True)),
                ('model', models.CharField(choices=[('belaz', 'БЕЛАЗ'), ('Komatsu', 'Komatsu')], max_length=10)),
                ('max_capacity', models.IntegerField(help_text='Макс. грузоподъемность (тонн)')),
                ('load_weight', models.IntegerField(help_text='Текущий груз(тонн)')),
                ('silicon_dioxide_percent', models.FloatField(verbose_name='SiO₂ (%)')),
                ('iron_percent', models.FloatField(verbose_name='Fe (%)')),
            ],
        ),
    ]
