# Generated by Django 5.2.2 on 2025-06-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_coords', models.TextField(default='30 10,40 40,20 40,10 20,30 10')),
                ('current_volume', models.IntegerField(default=900, help_text='Количество руды на складе')),
                ('silica_content', models.FloatField(default=34, verbose_name='SiO₂ (%)')),
                ('iron_content', models.FloatField(default=65, verbose_name='Fe (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Uploading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.FloatField(help_text='Координата точки разгрузки x')),
                ('y_coord', models.FloatField(help_text='Координата точки разгрузки y')),
                ('amount', models.IntegerField(help_text='Количество разгруженной руды')),
                ('is_unloaded_to_polygon', models.BooleanField(default=False)),
                ('truck_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
        ),
    ]
